### ISSUE TITLE
After update to ai sdk v5 execute function is not called for frontend tools

### ISSUE THREAD

**Issue by alexandrudanpop** [assistant-ui/assistant-ui#2327]
I can see the frontend tools correctly rendering, but the execute function is no longer triggered in the frontend.

Using `useChat` + `useAISDKRuntime`.

Tools are passed to useChat body using this approach, can correctly see them in the network tab
```
  const chat = useChat({
    id: chatId ?? undefined,
    transport: new DefaultChatTransport({
      api: '/api/v1/ai/conversation',
      headers: {
        Authorization: `Bearer ${authenticationSession.getToken()}`,
      },
      body: () => ({
        ...bodyRef.current,
        messages: messagesRef.current,
        tools: runtimeRef.current?.thread.getModelContext().tools ?? [],
      }),
    }),
```

<img width="892" height="366" alt="Image" src="https://github.com/user-attachments/assets/cf0c986d-6aeb-408b-8c38-3bb23f27d62c" />

the message stream looks like:
```
data: {"type":"start-step"}

data: {"type":"tool-input-start","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","toolName":"ui-navigate"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"{\""}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"url"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"\":"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"\"/"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"flows"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"/A"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"W"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"ew"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"D"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"IB"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"Y"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"Xd"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"Py"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"A"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"7"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"wy"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"fp"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"41"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"v"}

data: {"type":"tool-input-delta","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","inputTextDelta":"\"}"}

data: {"type":"tool-input-available","toolCallId":"call_oDCUiPP4pdLXoxZphsepQAnC","toolName":"ui-navigate","input":{"url":"/flows/AWewDIBYXdPyA7wyfp41v"}}

data: {"type":"finish-step"}

data: {"type":"finish"}
```

Packages used:
```
    "@assistant-ui/react": "0.10.41",
    "@assistant-ui/react-ai-sdk": "1.0.1",
      "ai": "5.0.2",
```

**Comment by Yonom** [comment]
Fixed in the latest version!

**Comment by alexandrudanpop** [comment]
Thanks for the quick response. I rechecked it and updated to the latest versions, but the frontend tools are still not executed.
```
 "@assistant-ui/react": "0.10.43",
 "@assistant-ui/react-ai-sdk": "1.0.4",
 "@assistant-ui/react-markdown": "0.10.9",
"@ai-sdk/react": "2.0.22",
```

**Comment by Yonom** [comment]
make sure to use AssistantChatTransport instead of DefaultChatTransport (the default transport does not send frontend tools to the backend) @alexandrudanpop 

we only support frontend tools with the new useChatRuntime, which has an identical API as useChat
