### ISSUE TITLE
Assistant Cloud Not Saving Messages after first assistant chat response.

### ISSUE THREAD

**Issue by geekfarmer** [assistant-ui/assistant-ui#2345]
When I'm using AssistantCloud with useChatRuntime. When I'm initializing new thread and start chatting with assistant then it generate the title and stored the messages in cloud but after that it's not saving data (messages) in assistant cloud. Can someone help here?

Here is my current DocumentAssistantProvider which is using AssistantProvider

```typescript
"use client";

import { TooltipProvider } from "@/components/ui/tooltip";
import { useCompanySessionContext } from "@/context/CompanySession";
import { useUserContext } from "@/context/User";
import {
  AssistantCloud,
  AssistantRuntime,
  AssistantRuntimeProvider,
  useAssistantInstructions,
} from "@assistant-ui/react";
import { useChatRuntime } from "@assistant-ui/react-ai-sdk";
import { Loader2 } from "lucide-react";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import AssistantApis from "@/actions/ai/data/assistant.data";
import { AssistantThread } from "@/types/ai/assistant";
import { ErrorProps } from "@/types/general";
import { isEmpty, isObject } from "lodash";
import { DocumentRawData } from "@/types/document";
import { getDocumentSystemPrompt } from "./document.prompt";

// Context for assistant configuration
interface AssistantContextType {
  runtime: AssistantRuntime;
  cloud: AssistantCloud;
}

const AssistantContext = createContext<AssistantContextType | null>(null);

// Hook to use assistant context
export const useAssistantContext = () => {
  const context = useContext(AssistantContext);
  if (!context) {
    throw new Error(
      "useAssistantContext must be used within AssistantProvider"
    );
  }
  return context;
};

export const useOptionalAssistantContext = () => {
  return useContext(AssistantContext);
};

// Base AssistantProvider with configuration
const AssistantProvider = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { userData } = useUserContext();
  const { currentUcrm } = useCompanySessionContext();

  // Generate workspace ID based on module and company/user
  const workspaceId = `${currentUcrm?.company?.id}_${userData?.id}`;

  const cloud = new AssistantCloud({
    baseUrl: "https://proj-0fkiu6jjk93q.assistant-api.com",
    authToken: async () => {
      try {
        const res = await fetch("/api/assistant-ui-token", {
          method: "POST",
          body: JSON.stringify({
            workspaceId,
            userId: userData?.id,
          }),
        });
        if (!res.ok) {
          throw new Error(`HTTP error! status: ${res.status}`);
        }
        const data = await res.json();
        return data.token;
      } catch (err) {
        console.error("Error fetching data:", err);
      }
    },
  });

  const runtime = useChatRuntime({
    cloud,
  });

  const contextValue: AssistantContextType = {
    runtime,
    cloud,
  };

  return (
    <AssistantContext.Provider value={contextValue}>
      <AssistantRuntimeProvider runtime={runtime}>
        <TooltipProvider>{children}</TooltipProvider>
      </AssistantRuntimeProvider>
    </AssistantContext.Provider>
  );
};

export default AssistantProvider;

// Specialized providers for different modules
export const DocumentAssistantProvider = ({
  children,
  documentId,
  rawData,
  documentName,
  documentType = "general",
}: {
  children: React.ReactNode;
  documentId: string;
  rawData?: DocumentRawData;
  documentName?: string | null;
  documentType?: string;
}) => {
  const { runtime: assistantRuntime } = useAssistantContext();
  const threadListRuntime = useMemo(
    () => assistantRuntime.threads,
    [assistantRuntime]
  );
  const [loading, setLoading] = useState(false);
  const [threadLoading, setThreadLoading] = useState(false);
  const [thread, setThread] = useState<AssistantThread>();
  const [error, setError] = useState<string>();

  // Track if we've already attempted to switch to this thread
  const hasAttemptedSwitch = useRef(false);
  const hasCompletedInitialFetch = useRef(false);
  const switchAttemptTimeout = useRef<NodeJS.Timeout | null>(null);

  const onError = (err: string | ErrorProps) => {
    setError(isObject(err) ? err.errors.message : err);
    setThreadLoading(false);
    hasCompletedInitialFetch.current = true;
  };

  const onThreadSuccess = (res: any) => {
    if (!isEmpty(res)) {
      setThread(res);
    }
    setThreadLoading(false);
    hasCompletedInitialFetch.current = true;
  };

  // Fetch assistant thread
  const fetchAssistantThread = useCallback(() => {
    if (documentId && !thread) {
      setThreadLoading(true);
      hasCompletedInitialFetch.current = false;
      return AssistantApis.getThread({
        entity: "document",
        entityId: documentId as string,
      }).then(onThreadSuccess, onError);
    }
  }, [documentId, thread]);

  // Create new thread and update existing DB record
  const createAndUpdateThread = useCallback(
    async (existingThread?: AssistantThread) => {
      try {
        setLoading(true);

        // Create new thread
        const { remoteId } = await threadListRuntime.mainItem.initialize();
        threadListRuntime.getState();

        if (existingThread) {
          // Update existing thread record with new remoteId
          await AssistantApis.updateThread(existingThread.id, {
            remoteId: remoteId,
          });
          console.log(
            `Updated existing thread for document ${documentId} with new remoteId: ${remoteId}`
          );
        } else {
          // Create new thread mapping
          await AssistantApis.createThread({
            entity: "document",
            entityId: documentId as string,
            remoteId: remoteId,
          });
          console.log(
            `Created new thread for document ${documentId} with remoteId: ${remoteId}`
          );
        }

        // Update local thread state with the new thread
        setThread({
          id: remoteId,
          entity: "document",
          entityId: documentId,
          remoteId: remoteId,
        });

        // Switch to the newly created thread
        threadListRuntime.switchToThread(remoteId);

        setLoading(false);
        hasAttemptedSwitch.current = true;
      } catch (error) {
        console.error("Error creating/updating thread:", error);
        onError("Failed to create or update chat thread");
      }
    },
    [documentId, threadListRuntime]
  );

  const createNewThread = useCallback(async () => {
    if (thread?.remoteId || !hasCompletedInitialFetch.current) return;
    await createAndUpdateThread();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [createAndUpdateThread, thread, hasCompletedInitialFetch.current]);

  // Reset the attempt flag when documentId changes (new document)
  useEffect(() => {
    hasAttemptedSwitch.current = false;
    hasCompletedInitialFetch.current = false;
  }, [documentId]);

  // Fetch thread when documentId is available
  useEffect(() => {
    fetchAssistantThread();
  }, [fetchAssistantThread]);

  // Handle thread switching once thread is fetched
  useEffect(() => {
    // Don't proceed if still loading, already attempted, or currently creating
    if (
      !thread?.remoteId ||
      hasAttemptedSwitch.current ||
      !hasCompletedInitialFetch.current
    )
      return;

    // If we have a thread, attempt to switch to it
    if (thread?.remoteId) {
      // Clear any existing timeout
      if (switchAttemptTimeout.current) {
        clearTimeout(switchAttemptTimeout.current);
      }

      const attemptSwitch = async () => {
        try {
          setLoading(true);
          const state = threadListRuntime.getState();

          // Check if threads are loaded and not empty
          if (state.isLoading) {
            // Retry after a short delay
            switchAttemptTimeout.current = setTimeout(attemptSwitch, 500);
            return;
          }

          // Check if the thread exists in assistant service
          const threadExists = state.threads.some(
            (threadId) => threadId === thread.remoteId
          );

          if (threadExists) {
            console.log("Thread found in assistant service.");
            await threadListRuntime.switchToThread(thread.remoteId);
            hasAttemptedSwitch.current = true;
          } else {
            console.log(
              "Thread not found in assistant service - creating new thread and updating DB record."
            );
            // Thread exists in DB but archived/deleted from assistant service
            // Create new thread and update the existing DB record
            await createAndUpdateThread(thread);
          }
          setLoading(false);
        } catch (error) {
          setLoading(false);
          console.error("Error switching thread:", error);
          hasAttemptedSwitch.current = true;
        }
      };

      // Only attempt if we haven't already tried
      if (!hasAttemptedSwitch.current) {
        // Start the attempt process
        attemptSwitch();
      }
    }

    // Cleanup function
    return () => {
      if (switchAttemptTimeout.current) {
        clearTimeout(switchAttemptTimeout.current);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    threadListRuntime,
    thread,
    hasCompletedInitialFetch.current,
    createAndUpdateThread,
  ]);

  useEffect(() => {
    createNewThread();
  }, [createNewThread]);

  const systemPrompt = useMemo(() => {
    return getDocumentSystemPrompt({
      documentId,
      documentType,
      documentName,
      rawData,
    });
  }, [documentId, documentType, documentName, rawData]);

  useAssistantInstructions({
    instruction: systemPrompt,
  });

  if (threadLoading || loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <p className="text-red-500 mb-2">Error loading chat</p>
          <p className="text-sm text-gray-500">{error}</p>
        </div>
      </div>
    );
  }

  return children;
};

```

**Comment by grski** [comment]
We are having the same issue.

**Comment by Yonom** [comment]
Thank you, fixed in https://github.com/assistant-ui/assistant-ui/pull/2372/files

**Comment by grski** [comment]
@Yonom 
There's an improvement however now POST /messages seems to return 500 in some cases preventing the persistance of some messages

<img width="984" height="455" alt="Image" src="https://github.com/user-attachments/assets/c28413ba-fc88-4a17-9ccb-d40927a96daa" />

After refreshing the page: 

<img width="984" height="471" alt="Image" src="https://github.com/user-attachments/assets/32c8a351-72f6-4de5-88f6-95fec1cb4b7f" />

**Comment by Yonom** [comment]
Should be fixed now, thanks!

**Comment by frasalvi** [comment]
@Yonom I tried today on the latest version, and I still experience the same issue (see #2596).
